version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: go
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Указываем том для хранения данных

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/go
      
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
    - "5500:80"

volumes:
  db_data:  # Определяем том