version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: go
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Указываем том для хранения данных

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Порт для доступа к Redis

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/go
      MAILCODESEND: ${MAILCODESEND}
      SMTPPASSWORD: ${SMTPPASSWORD}
      
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
    - "5500:80"

volumes:
  db_data: